DROP TABLE SAMPLE_T; -- 기존이름이랑 충돌나면 안되니까 삭제먼저

CREATE TABLE SAMPLE_T(
    SAMPLE_NO       NUMBER              NOT NULL,
    SAMPLE_CONTENT  VARCHAR2(100 BYTE),
    SAMPLE_EDITOR   VARCHAR2(100 BYTE),
    SAMPLE_DT       DATE,
    CONSTRAINT PK_SAMPLE PRIMARY KEY(SAMPLE_NO)
);

DROP SEQUENCE SAMPLE_SEQ;
CREATE SEQUENCE SAMPLE_SEQ NOCACHE;    
    
